name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova App & Build APK
        run: |
          cordova create myApp com.bgz.busapp "BusesOfGabtoli"
          cd myApp
          cordova platform add android
          rm -rf www/*
          cp -r ../index.html www/
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: App-Release-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
